# Generated by Django 6.0.4 on 2026-05-03 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in XAF')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=15)),
                ('external_ref', models.CharField(blank=True, help_text='MoMo/Orange transaction ref', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(max_length=20, unique=True)),
                ('method', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='processing', max_length=15)),
                ('payout_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payout_date'],
            },
        ),
    ]
