# Generated by Django 4.2.30 on 2026-06-24 06:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payout_add_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_commission', models.DecimalField(decimal_places=4, default=Decimal('0.07'), max_digits=6)),
                ('growth_commission', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=6)),
                ('premium_commission', models.DecimalField(decimal_places=4, default=Decimal('0.04'), max_digits=6)),
                ('escrow_release_hours', models.PositiveIntegerField(default=72)),
                ('dispute_window_hours', models.PositiveIntegerField(default=48)),
                ('free_shop_max_products', models.PositiveIntegerField(default=20)),
                ('premium_shop_max_products', models.PositiveIntegerField(default=500)),
                ('max_images_per_listing', models.PositiveIntegerField(default=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform configuration',
            },
        ),
    ]
