# Generated by Django 6.0.4 on 2026-05-03 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('wrong_item', 'Wrong item received'), ('damaged', 'Damaged on arrival'), ('not_delivered', 'Item never delivered'), ('not_as_described', 'Not as described'), ('counterfeit', 'Counterfeit suspected')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('urgent', 'Urgent'), ('in_review', 'In review'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('resolution', models.CharField(blank=True, choices=[('refund_buyer', 'Full refund to buyer'), ('release_vendor', 'Release to vendor'), ('partial_refund', 'Partial refund')], max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
