# Generated by Django 4.2.30 on 2026-05-24 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('identity', 'National ID / Passport'), ('driving_license', 'Driving license'), ('vehicle', 'Vehicle registration'), ('address', 'Address proof')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='agent_kyc/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
