# Generated by Django 4.2.30 on 2026-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('under_review', 'Under review'), ('rejected', 'Rejected')], default='under_review', max_length=15),
        ),
    ]
