# Generated by Django 4.2.30 on 2026-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_submitted', 'Not submitted')], default='not_submitted', max_length=15),
        ),
    ]
