# Generated by Django 4.2.30 on 2026-06-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shop_status_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
    ]
