# Generated by Django 4.2.17 on 2026-07-01 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('verified', 'Verified'), ('pro_seller', 'Pro Seller')], default='starter', max_length=15),
        ),
        migrations.AddField(
            model_name='shop',
            name='tier2_application_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
