# Generated by Django 4.2.30 on 2026-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('paid_escrow', 'Paid — escrow held'), ('preparing', 'Preparing'), ('agent_assigned', 'Agent assigned'), ('picked_up', 'Picked up'), ('in_transit', 'In transit'), ('delivered_confirm', 'Delivered — confirm'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_resolved', 'Partially resolved')], default='awaiting_payment', max_length=20),
        ),
    ]
