# Generated by Django 4.2.30 on 2026-06-10 06:33

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_clear_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=products.models._product_image_path),
        ),
    ]
